export const HEALTH_TIPS_DATA = {
  appInfo: {
    name: "Bump2Baby Health Tips",
    version: "1.0.0",
    lastUpdated: "2026-01-14",
    disclaimer:
      "This information is for educational purposes only and does not replace professional medical advice. Always consult a qualified healthcare provider.",
  },

  categories: [
    {
      id: "general_wellness",
      title: "General Wellness",
      tips: [
        {
          id: "gw_001",
          title: "Stay Hydrated During Pregnancy",
          summary:
            "Proper hydration is crucial during pregnancy for amniotic fluid, blood volume, and preventing complications.",
          guidance: [
            "Drink 10-12 glasses of water daily during pregnancy",
            "Increase intake if experiencing morning sickness",
            "Carry a water bottle to sip throughout the day",
            "Monitor urine color - pale yellow indicates good hydration",
            "Limit caffeine to 200mg per day (about 1-2 cups of coffee)",
          ],
          audience: "Pregnant women",
          severity: "medium",
          whenToSeeDoctor: [
            "Signs of dehydration (dark urine, dizziness, rapid heartbeat)",
            "Severe vomiting preventing fluid intake",
            "Decreased fetal movement",
          ],
        },
        {
          id: "gw_002",
          title: "Sleep During Pregnancy",
          summary:
            "Quality sleep supports fetal development and maternal health.",
          guidance: [
            "Sleep on your left side to improve blood flow to the baby",
            "Use pregnancy pillows for support",
            "Establish a relaxing bedtime routine",
            "Avoid large meals 2-3 hours before bed",
            "Take short naps during the day if needed",
            "Elevate your head if experiencing heartburn",
          ],
          audience: "Pregnant women",
          severity: "low",
        },
        {
          id: "gw_003",
          title: "Safe Exercise During Pregnancy",
          summary:
            "Regular exercise helps maintain fitness and prepares your body for labor.",
          guidance: [
            "Aim for 30 minutes of moderate exercise most days",
            "Try prenatal yoga, swimming, or walking",
            "Avoid contact sports and activities with fall risk",
            "Stay cool and hydrated during exercise",
            "Stop if you feel dizzy, short of breath, or experience pain",
            "Wear supportive shoes and comfortable clothing",
          ],
          audience: "Pregnant women",
          severity: "medium",
          whenToSeeDoctor: [
            "Vaginal bleeding or fluid leakage",
            "Chest pain or severe shortness of breath",
            "Regular painful contractions",
            "Calf pain or swelling",
          ],
        },
        {
          id: "gw_004",
          title: "Postpartum Recovery",
          summary: "Your body needs time to heal after childbirth.",
          guidance: [
            "Rest as much as possible - sleep when baby sleeps",
            "Accept help from family and friends",
            "Avoid heavy lifting for 4-6 weeks",
            "Do pelvic floor exercises (Kegels) to strengthen muscles",
            "Wear supportive undergarments",
            "Take prescribed pain medication as needed",
            "Gradually increase activity levels",
          ],
          audience: "New mothers",
          severity: "high",
          whenToSeeDoctor: [
            "Heavy bleeding (soaking more than one pad per hour)",
            "Fever over 100.4°F (38°C)",
            "Severe abdominal pain",
            "Foul-smelling vaginal discharge",
            "Red, swollen, or painful breasts",
            "Thoughts of harming yourself or baby",
          ],
        },
        {
          id: "gw_005",
          title: "Newborn Sleep Safety",
          summary:
            "Safe sleep practices reduce the risk of SIDS (Sudden Infant Death Syndrome).",
          guidance: [
            "Always place baby on their back to sleep",
            "Use a firm, flat sleep surface with fitted sheet",
            "Keep crib free of blankets, pillows, and toys",
            "Room-share without bed-sharing for first 6 months",
            "Maintain comfortable room temperature (68-72°F)",
            "Offer a pacifier at nap and bedtime",
            "Avoid smoke exposure",
          ],
          audience: "New parents",
          severity: "high",
        },
        {
          id: "gw_006",
          title: "Baby Bathing Basics",
          summary: "Proper bathing keeps baby clean and comfortable.",
          guidance: [
            "Give sponge baths until umbilical cord falls off",
            "Bathe 2-3 times per week (daily baths not necessary)",
            "Use warm water (test with elbow - should feel comfortable)",
            "Use mild, fragrance-free baby soap",
            "Never leave baby unattended in water",
            "Support baby's head and neck at all times",
            "Pat dry gently and apply moisturizer if needed",
          ],
          audience: "New parents",
          severity: "medium",
        },
      ],
    },

    {
      id: "nutrition",
      title: "Nutrition & Diet",
      tips: [
        {
          id: "nt_001",
          title: "Prenatal Nutrition Essentials",
          summary:
            "Proper nutrition supports healthy fetal development and maternal health.",
          guidance: [
            "Take prenatal vitamins with folic acid (400-800 mcg daily)",
            "Eat iron-rich foods (lean meat, beans, fortified cereals)",
            "Include calcium sources (dairy, leafy greens, fortified foods)",
            "Consume omega-3 fatty acids (salmon, walnuts, flaxseed)",
            "Eat small, frequent meals to manage nausea",
            "Choose whole grains, fruits, and vegetables",
            "Aim for 300 extra calories per day in 2nd and 3rd trimesters",
          ],
          audience: "Pregnant women",
          severity: "high",
        },
        {
          id: "nt_002",
          title: "Foods to Avoid During Pregnancy",
          summary:
            "Certain foods pose risks during pregnancy and should be avoided.",
          guidance: [
            "Avoid raw or undercooked meat, eggs, and seafood",
            "Skip unpasteurized dairy products and soft cheeses",
            "Limit high-mercury fish (shark, swordfish, king mackerel)",
            "Avoid deli meats unless heated until steaming",
            "Skip raw sprouts and unwashed produce",
            "Limit caffeine to 200mg per day",
            "Avoid alcohol completely",
            "Skip herbal supplements without doctor approval",
          ],
          audience: "Pregnant women",
          severity: "high",
        },
        {
          id: "nt_003",
          title: "Breastfeeding Nutrition",
          summary:
            "Nursing mothers need extra nutrients to support milk production.",
          guidance: [
            "Consume an extra 450-500 calories per day",
            "Drink plenty of water (aim for 13 cups daily)",
            "Continue taking prenatal vitamins",
            "Eat protein-rich foods at each meal",
            "Include healthy fats (avocado, nuts, olive oil)",
            "Limit caffeine and monitor baby's reaction",
            "Avoid alcohol or wait 2-3 hours after drinking to nurse",
            "Eat a variety of foods to expose baby to different flavors",
          ],
          audience: "Breastfeeding mothers",
          severity: "medium",
        },
        {
          id: "nt_004",
          title: "Managing Morning Sickness",
          summary: "Dietary strategies can help reduce nausea and vomiting.",
          guidance: [
            "Eat small, frequent meals throughout the day",
            "Keep crackers by your bedside for morning",
            "Try ginger tea, ginger candies, or ginger ale",
            "Avoid strong smells and greasy foods",
            "Eat protein-rich snacks before bed",
            "Stay hydrated with small sips of water",
            "Try cold foods if hot foods trigger nausea",
            "Consider vitamin B6 supplements (consult doctor first)",
          ],
          audience: "Pregnant women (1st trimester)",
          severity: "medium",
          whenToSeeDoctor: [
            "Unable to keep any food or liquids down",
            "Weight loss of more than 5% of pre-pregnancy weight",
            "Dark urine or decreased urination",
            "Dizziness or fainting",
          ],
        },
        {
          id: "nt_005",
          title: "Starting Solid Foods for Baby",
          summary:
            "Introducing solids is an exciting milestone around 6 months.",
          guidance: [
            "Wait until baby is around 6 months old",
            "Look for readiness signs (sitting up, showing interest in food)",
            "Start with single-ingredient purees (rice cereal, sweet potato)",
            "Introduce one new food at a time, waiting 3-5 days",
            "Offer iron-rich foods (meat, beans, fortified cereals)",
            "Avoid honey until after 12 months (botulism risk)",
            "Skip added salt, sugar, and choking hazards",
            "Continue breastfeeding or formula feeding",
          ],
          audience: "Parents of 6+ month babies",
          severity: "medium",
        },
        {
          id: "nt_006",
          title: "Gestational Diabetes Diet",
          summary:
            "Managing blood sugar through diet protects both mother and baby.",
          guidance: [
            "Eat balanced meals with protein, healthy fats, and complex carbs",
            "Choose whole grains over refined carbohydrates",
            "Include fiber-rich foods to slow sugar absorption",
            "Eat smaller, more frequent meals",
            "Monitor carbohydrate portions at each meal",
            "Pair carbs with protein to stabilize blood sugar",
            "Avoid sugary drinks and desserts",
            "Test blood sugar as directed by your healthcare provider",
          ],
          audience: "Women with gestational diabetes",
          severity: "high",
          whenToSeeDoctor: [
            "Blood sugar levels outside target range",
            "Difficulty managing diet alone",
            "Signs of high blood sugar (excessive thirst, frequent urination)",
          ],
        },
      ],
    },

    {
      id: "mental_health",
      title: "Mental Health",
      tips: [
        {
          id: "mh_001",
          title: "Managing Pregnancy Anxiety",
          summary:
            "It's normal to feel anxious during pregnancy, but there are ways to cope.",
          guidance: [
            "Practice prenatal yoga or meditation",
            "Join a pregnancy support group",
            "Talk openly with your partner about fears",
            "Limit exposure to negative birth stories",
            "Stay informed but avoid excessive research",
            "Maintain regular prenatal appointments",
            "Practice deep breathing exercises",
            "Consider therapy if anxiety is overwhelming",
          ],
          audience: "Pregnant women",
          severity: "medium",
          whenToSeeDoctor: [
            "Constant worry interfering with daily life",
            "Panic attacks",
            "Difficulty sleeping due to anxiety",
            "Thoughts of harming yourself",
          ],
        },
        {
          id: "mh_002",
          title: "Postpartum Depression Awareness",
          summary:
            "PPD affects 1 in 7 new mothers and is treatable with proper support.",
          guidance: [
            "Recognize symptoms: persistent sadness, hopelessness, irritability",
            "Don't blame yourself - PPD is not your fault",
            "Reach out to your healthcare provider immediately",
            "Accept help from family and friends",
            "Prioritize self-care and rest",
            "Join a new mothers' support group",
            "Consider therapy and/or medication",
            "Know that treatment works and you will feel better",
          ],
          audience: "New mothers",
          severity: "high",
          whenToSeeDoctor: [
            "Symptoms lasting more than 2 weeks",
            "Difficulty bonding with baby",
            "Thoughts of harming yourself or baby",
            "Inability to care for yourself or baby",
            "Severe mood swings",
          ],
        },
        {
          id: "mh_003",
          title: "Partner Support During Pregnancy",
          summary: "Partners play a crucial role in maternal mental health.",
          guidance: [
            "Attend prenatal appointments together",
            "Learn about pregnancy and childbirth",
            "Help with household tasks and errands",
            "Listen without judgment to concerns and fears",
            "Encourage self-care and rest",
            "Plan date nights to maintain connection",
            "Take childbirth and parenting classes together",
            "Watch for signs of depression or anxiety",
          ],
          audience: "Partners of pregnant women",
          severity: "medium",
        },
        {
          id: "mh_004",
          title: "Self-Care for New Mothers",
          summary:
            "Taking care of yourself helps you better care for your baby.",
          guidance: [
            "Rest whenever possible - sleep when baby sleeps",
            "Shower and get dressed daily",
            "Eat nutritious meals and stay hydrated",
            "Get outside for fresh air and sunlight",
            "Connect with other new mothers",
            "Ask for and accept help",
            "Set realistic expectations",
            "Take breaks from baby care when possible",
          ],
          audience: "New mothers",
          severity: "medium",
        },
        {
          id: "mh_005",
          title: "Coping with Infant Crying",
          summary: "All babies cry, and it's okay to feel frustrated.",
          guidance: [
            "Check for basic needs: hunger, diaper, temperature",
            "Try the 5 S's: swaddle, side position, shush, swing, suck",
            "Take baby for a walk or car ride",
            "Use white noise or gentle music",
            "If overwhelmed, place baby safely in crib and take a break",
            "Never shake a baby - call for help if needed",
            "Remember: crying peaks around 6-8 weeks and improves",
            "Reach out to pediatrician if crying seems excessive",
          ],
          audience: "New parents",
          severity: "high",
        },
      ],
    },

    {
      id: "chronic_conditions",
      title: "Chronic Condition Care",
      tips: [
        {
          id: "cc_001",
          title: "Managing High Blood Pressure in Pregnancy",
          summary: "Hypertension during pregnancy requires careful monitoring.",
          guidance: [
            "Attend all prenatal appointments for blood pressure checks",
            "Reduce sodium intake (limit to 2,300mg daily)",
            "Eat potassium-rich foods (bananas, sweet potatoes)",
            "Rest on your left side to improve blood flow",
            "Monitor for symptoms of preeclampsia",
            "Take prescribed medications exactly as directed",
            "Avoid NSAIDs unless approved by doctor",
            "Reduce stress through relaxation techniques",
          ],
          audience: "Pregnant women with hypertension",
          severity: "high",
          whenToSeeDoctor: [
            "Severe headache that won't go away",
            "Vision changes (blurriness, seeing spots)",
            "Severe swelling of hands, face, or feet",
            "Upper abdominal pain",
            "Sudden weight gain",
            "Decreased fetal movement",
          ],
        },
        {
          id: "cc_002",
          title: "Diabetes Management During Pregnancy",
          summary:
            "Controlling blood sugar is essential for a healthy pregnancy.",
          guidance: [
            "Check blood sugar levels as prescribed",
            "Follow your meal plan carefully",
            "Take insulin or medications as directed",
            "Exercise regularly with doctor approval",
            "Keep detailed records of blood sugar readings",
            "Attend all prenatal and endocrinology appointments",
            "Carry glucose tablets for low blood sugar",
            "Monitor for signs of high or low blood sugar",
          ],
          audience: "Pregnant women with diabetes",
          severity: "high",
          whenToSeeDoctor: [
            "Blood sugar consistently outside target range",
            "Signs of diabetic ketoacidosis",
            "Frequent episodes of low blood sugar",
            "Difficulty managing diet and medication",
          ],
        },
        {
          id: "cc_003",
          title: "Asthma Control During Pregnancy",
          summary:
            "Well-controlled asthma is important for oxygen supply to baby.",
          guidance: [
            "Continue asthma medications as prescribed",
            "Avoid known triggers (smoke, allergens, cold air)",
            "Use peak flow meter to monitor lung function",
            "Keep rescue inhaler with you at all times",
            "Get flu and whooping cough vaccines",
            "Inform your obstetrician about your asthma",
            "Have an asthma action plan",
            "Don't stop medications without consulting doctor",
          ],
          audience: "Pregnant women with asthma",
          severity: "high",
          whenToSeeDoctor: [
            "Increased use of rescue inhaler",
            "Difficulty breathing or talking",
            "Lips or fingernails turning blue",
            "Severe chest tightness",
            "No improvement after using rescue inhaler",
          ],
        },
        {
          id: "cc_004",
          title: "Thyroid Disorders in Pregnancy",
          summary: "Thyroid hormone levels affect fetal brain development.",
          guidance: [
            "Take thyroid medication on empty stomach",
            "Get thyroid levels checked regularly",
            "Don't take thyroid medication with prenatal vitamins",
            "Report symptoms of hypo or hyperthyroidism",
            "Attend all endocrinology appointments",
            "Medication doses may need adjustment during pregnancy",
            "Avoid iodine supplements unless prescribed",
          ],
          audience: "Pregnant women with thyroid disorders",
          severity: "high",
          whenToSeeDoctor: [
            "Symptoms of hyperthyroidism (rapid heartbeat, weight loss)",
            "Symptoms of hypothyroidism (fatigue, weight gain, depression)",
            "Neck swelling or pain",
          ],
        },
        {
          id: "cc_005",
          title: "Baby Eczema Management",
          summary: "Gentle skin care can help manage infant eczema.",
          guidance: [
            "Bathe baby in lukewarm water for 5-10 minutes",
            "Use fragrance-free, gentle cleansers",
            "Apply thick moisturizer immediately after bathing",
            "Dress baby in soft, breathable cotton clothing",
            "Keep baby's nails short to prevent scratching",
            "Avoid known triggers (certain fabrics, soaps)",
            "Use prescribed steroid creams as directed",
            "Maintain comfortable room temperature",
          ],
          audience: "Parents of babies with eczema",
          severity: "medium",
          whenToSeeDoctor: [
            "Signs of skin infection (oozing, crusting, fever)",
            "Eczema not improving with treatment",
            "Baby seems very uncomfortable or not sleeping",
            "Eczema spreading rapidly",
          ],
        },
      ],
    },
  ],
};
